//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicRow
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public System.DateTime Data_otwarcia { get; set; }
        public bool Prywatna { get; set; }
        public decimal Ocena { get; set; }
        public string Lokalizacja { get; set; }
        public string Kierownik { get; set; }
    }
}
