//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicDataEntities : DbContext
    {
        public ClinicDataEntities()
            : base("name=ClinicDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clinics> Clinics { get; set; }
        public virtual DbSet<Costs> Costs { get; set; }
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Localizations> Localizations { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Opinions> Opinions { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersTools> OrdersTools { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Producents> Producents { get; set; }
        public virtual DbSet<Registrations> Registrations { get; set; }
        public virtual DbSet<Tools> Tools { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ClinicRow> ClinicRow { get; set; }
        public virtual DbSet<CostRow> CostRow { get; set; }
        public virtual DbSet<DrugRow> DrugRow { get; set; }
        public virtual DbSet<EmployeeRow> EmployeeRow { get; set; }
        public virtual DbSet<LocalizationRow> LocalizationRow { get; set; }
        public virtual DbSet<OperationRow> OperationRow { get; set; }
        public virtual DbSet<OpinionRow> OpinionRow { get; set; }
        public virtual DbSet<OrderRow> OrderRow { get; set; }
        public virtual DbSet<OrderToolRow> OrderToolRow { get; set; }
        public virtual DbSet<PatientRow> PatientRow { get; set; }
        public virtual DbSet<ProducentRow> ProducentRow { get; set; }
        public virtual DbSet<RegistrationRow> RegistrationRow { get; set; }
        public virtual DbSet<ToolRow> ToolRow { get; set; }
    }
}
