//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugRow
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public Nullable<byte> Dawka { get; set; }
        public System.DateTime Data_produkcji { get; set; }
        public System.DateTime Data_ważności { get; set; }
        public bool Psychotropowe { get; set; }
        public byte Ilość_dostępna { get; set; }
        public string Jednostka { get; set; }
    }
}
