//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinions
    {
        public int Id { get; set; }
        public int ClinicId { get; set; }
        public int DataId { get; set; }
        public byte Mark { get; set; }
    
        public virtual Clinics Clinics { get; set; }
        public virtual Data Data { get; set; }
    }
}
