//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderToolRow
    {
        public int Id { get; set; }
        public Nullable<byte> Ilosc { get; set; }
        public string Przychodnia { get; set; }
        public string Narzedzie { get; set; }
        public string Producent { get; set; }
    }
}
