//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRow
    {
        public int Id { get; set; }
        public string Pacjent { get; set; }
        public string Operacja { get; set; }
        public System.DateTime Planowana_data { get; set; }
        public Nullable<byte> Priorytet { get; set; }
    }
}
