//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public int EmployeeId { get; set; }
        public int PatientId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
