//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationRow
    {
        public int Id { get; set; }
        public string Pacjent { get; set; }
        public string Lekarz { get; set; }
        public System.DateTime Data_operacji { get; set; }
        public string Czas_rozpoczęcia { get; set; }
    }
}
