//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolRow
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public byte Ilosc_dostepna { get; set; }
        public System.DateTime Data_produkcji { get; set; }
        public System.DateTime Data_wazno_ci { get; set; }
        public string Opis { get; set; }
    }
}
